### ISSUE TITLE
Wrong member name, must be elementClass

### ISSUE THREAD

**Issue by xperiments** [lokalise/node-lokalise-api#1]
begin working with the api, get this error:

"UnhandledPromiseRejectionWarning: TypeError: childClass.elementClass is not a constructor"

I think is a typo error.

https://github.com/lokalise/node-lokalise-api/blob/725240dc43a9839d5863221217018021bd8a7a6e/src/collections/files.ts#L10

needs to be:

```
protected static elementClass: Object = File;
```

**Comment by kutanov** [comment]
Thank you!
