### ISSUE TITLE
Add commit message field to files/download endpoint

### ISSUE THREAD

**Issue by alexbrazier** [lokalise/node-lokalise-api#17]
**The feature I'd like is...**

Add the commit message field when using the `github` or other vcs provider as seen on the UI to export your translations.

We use this field because we want to specify a ticket number and a `[skip ci]` message in the commit message to stop the CI from running the build on an automated translation updated and to pass our ticket check.

**Additional context**

example query:

`POST /projects/<id>/files/download`
```js
{
  ...,
  triggers: ['github'],
  // Does not exist yet
  commit_template: '[JIRA-123] [skip ci] Lokalise: Translations update'
}
```

**Comment by bodrovis** [comment]
Hello and thanks for reaching us out! We will discuss this with the product team.

**Comment by alexbrazier** [comment]
Thanks @bodrovis, are there any updates on this?

**Comment by bodrovis** [comment]
@alexbrazier I'll double check this for you, sorry for long wait!

**Comment by bodrovis** [comment]
So, this was registered at our product board, but unfortunately I can't give you any ETA yet :( We have lots of planned features to release, so it's quite hard to say when this is going to go live. As soon as there's any updates on this request, I'll let you know!

**Comment by alexbrazier** [comment]
Great, thanks for the update!

**Comment by bodrovis** [comment]
I'm going to close this issue as it's not directly related to Node SDK but rather to Lokalise API in general. The team is aware of this feature request but I cannot say if and when it is going to be released, unfortunately — we have lots of features and enhancements in the pipeline. However, if this feature is cruicial, I would recommend contacting the support team or CSM directly (if you have one assigned) and providing the context.
