### ISSUE TITLE
UploadFileParams uses old paramter: convert_placeholder

### ISSUE THREAD

**Issue by chrisdchow** [lokalise/node-lokalise-api#192]
**Describe the bug**
File upload does not respect `convert_placeholder` parameter.

**To Reproduce**
1. Use the node-js-api to upload a File.
2. Set convert_placeholder to `false`.
```
await this.lokaliseApi.files.upload(this.projectId, {
  data: content,
  filename: fileName,
  lang_iso: languageISOCode,
  convert_placeholder: false,
  tags: ['Pushed'],
  replace_modified: this.replaceModified,
  skip_detect_lang_iso: true,
})
```
3. File in Lokalise uses the Lokalise universal placeholder

**Expected behavior**
I expect the original placeholder to preserved.

**Your environment:**
 - Node version: 12.22.3

**Additional context**
UploadFileParams does not use `convert_placeholders` which is the correct param in the latest version of the API.  https://app.lokalise.com/api2docs/curl/#transition-upload-a-file-post. Rather it uses `convert_placeholder`, without the s. I contacted someone on Lokalise support and they mentioned `convert_placeholder` is the V1 version of that param.

**Comment by bodrovis** [comment]
Hello, thank you for reporting this! I'll fix asap.
