### ISSUE TITLE
lokaliseApi.queuedProcesses.get

### ISSUE THREAD

**Issue by hzpeng57** [lokalise/node-lokalise-api#260]
**Describe the bug**
This is my code

![image](https://user-images.githubusercontent.com/31138343/150299774-02efb9a5-e5f9-4cd1-9628-7e03c7182d11.png)

I get error "lokaliseApi.queuedProcesses.get is not a function"

If i change my code to `process = await lokaliseApi.queuedProcesses().get(process.process_id, { project_id: projectId });`

I will get 
```
running upload success // should show: finish upload success?
```
in console

It looks like asynchronous functions don't work and the example on the official documentation has an error

[https://lokalise.github.io/node-lokalise-api/api/files](https://lokalise.github.io/node-lokalise-api/api/files)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Your environment:**
 - Node version

**Additional context**

**Comment by bodrovis** [comment]
I've also prepared a tutorial on this topic, so you might find the following section useful https://lokalise.com/blog/lokalise-apiv2-in-practice/#In_TypeScript-3
