### ISSUE TITLE
Clarification on screenshots vs snapshots

### ISSUE THREAD

**Issue by maribies** [lokalise/node-lokalise-api#3]
In the README you have the snap shot commands as `lokaliseApi.screenshots.{whatever}` is this in fact correct?

**Comment by bodrovis** [comment]
Okay, so this is definitely a mistake. Screenshots are used to upload images for translation extraction. Snapshot is a backup of the project.

**Comment by bodrovis** [comment]
Fixed, thanks for reporting this!
