### ISSUE TITLE
Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by iluvmemes** [lokalise/node-lokalise-api#301]
**Describe the bug**
The api has a dependency on `got` which subsequently has a dependency on `cacheable-lookup`.  That package has a dependency on `dns` however, it's package.json doesn't include it.  As a result, it never gets installed.  This causes the following error.

```
info  - automatically enabled Fast Refresh for 1 custom loader
error - ../../node_modules/cacheable-lookup/source/index.js:10:2
Module not found: Can't resolve 'dns'

Import trace for requested module:
../../node_modules/got/dist/source/core/index.js
../../node_modules/got/dist/source/create.js
../../node_modules/got/dist/source/index.js
../../node_modules/@lokalise/node-api/dist/oauth2/auth_request.js
../../node_modules/@lokalise/node-api/dist/oauth2/lokalise_auth.js
../../node_modules/@lokalise/node-api/dist/main.js
../../node_modules/@lokalise/node-api/index.js
./components/Hero/Hero.tsx
./components/index.ts
./pages/_app.tsx
```

see: 

[https://github.com/szmarczak/cacheable-lookup/blob/master/source/index.js#L10](https://github.com/szmarczak/cacheable-lookup/blob/master/source/index.js#L10)

[https://github.com/szmarczak/cacheable-lookup/blob/master/package.json](https://github.com/szmarczak/cacheable-lookup/blob/master/package.json)

**To Reproduce**
Install the api, import it into your code, attempt to instantiate the class.

**Expected behavior**
It should not have any dependency errors.

**Your environment:**
 - Node version: v16.14.2

**Comment by bodrovis** [comment]
Unfortunately I can't reproduce this issue. I've just created a new project and this code does not raise any errors:

```js
const { LokaliseApi } = require('@lokalise/node-api');

const lokaliseApi = new LokaliseApi({ apiKey: '<apiKey>'});
```

Could you please prepare a small code sample or a repo reproducing this issue? Got indeed does have this dependency listed but it should be installed automatically: I don't think it's required to list it in the package.json file.

**Comment by alicedomingueslok** [comment]
I removed @lokalise from node modules, performed a new npm install and successfully ran the same.
It seems local.

**Comment by iluvmemes** [comment]
Thank you for looking into this.  From your comments I'm thinking you're right and it is local.  I'll continue to look at it from my end.
