### ISSUE TITLE
Using this lib with Deno

### ISSUE THREAD

**Issue by oskarkivra** [lokalise/node-lokalise-api#350]
## Support Deno

It is possible to use this lib with Deno:
```ts
import { LokaliseApi } from "npm:@lokalise/node-api";

new LokaliseApi({ apiKey });
```

However, since you are importing `package.json` to get the current version. E.g. here: https://github.com/lokalise/node-lokalise-api/blob/e5040276bea764abc944edb31b74b449ddd60769/src/http_client/base.ts#L3 it is required to create a `package.json` file next to the Deno script to get this working.

It would be awesome to support Deno. Is it possible to get the version number in some other way?

**Comment by bodrovis** [comment]
I don't think there's any other way really except for writing the version manually but it's quite tedious. Theoretically, we can simply check if the `package.json` file is present and if not, set the version to unknown or something like that. If that would work for you, I can release a new version

**Comment by oskarkivra** [comment]
Correct me if I'm wrong but will `readFile("./package.json")` not read the `package.json` that exists in the same dir as `cwd`? Do this work as intended? Should it not be:
```ts
const pkg = JSON.parse((await readFile(new URL("../../package.json", import.meta.url))).toString()); 
```

**Comment by bodrovis** [comment]
That's a good question. Currently everything works fine with regular setups: I don't observe any issues with tests or trying to run this locally. I'm doing some fixes at the moment to check whether the package.json actually exists and I'll also try your solution

**Comment by bodrovis** [comment]
@oskarkivra The latest commit should hopefully fix this https://github.com/lokalise/node-lokalise-api/commit/747ab8c8a9e7abae546fbdb252e8453dd9eccd26. Could you please try installing directly from GH and let me know if it works now?

**Comment by oskarkivra** [comment]
Thanks for the fast reply.
I don't know if I can test this with deno in an easy way. When importing `npm:@lokalise/node-api` deno will run the code in compatible mode to support node.js-code, but when pointing out a URL to github I do not think I can tell deno to run in compatible mode.

**Comment by oskarkivra** [comment]
But I can close this issue and test it once it is publish to npm. No rush.

**Comment by bodrovis** [comment]
Sure, I'll release a new version now. Please let me know how it goes

**Comment by oskarkivra** [comment]
Thnaks! It worked. It is not perfect but now I don't need to create a package.json file anymore:

_cat test.ts_
```ts
import { LokaliseApi } from "npm:@lokalise/node-api";

const api = new LokaliseApi({
  apiKey: "...",
});

api.keys().get(123, {
  project_id: "...",
});
```

```
➜ deno run test.ts
✅ Granted read access to "Library/Caches/deno/npm/registry.npmjs.org/@lokalise/node-api/9.4.0/package.json".
✅ Granted net access to "api.lokalise.com".
error: Uncaught { message: "Not Found", code: 404 }

➜ deno run test.ts
❌ Denied read access to "Library/Caches/deno/npm/registry.npmjs.org/@lokalise/node-api/9.4.0/package.json".
✅ Granted net access to "api.lokalise.com".
error: Uncaught { message: "Not Found", code: 404 }
```

**Comment by bodrovis** [comment]
Good! Any other suggestions on how to make things even better? :)

**Comment by oskarkivra** [comment]
No, not really. I think this is the best way for now. Thanks for your work!

**Comment by bodrovis** [comment]
Thank you for the feedback and have a happy New Year 🥳
