### ISSUE TITLE
Support Remove Key from Task API

### ISSUE THREAD

**Issue by jinsu3758** [lokalise/node-lokalise-api#390]
Currently, there is no API to remove keys from within a task. I want to automate task creation, but I need to put in a key every time, so I want to create a temporary key and remove it, but I can't remove the key once I'm inside the task.

**Comment by bodrovis** [comment]
Good day! Could you please send this feature request via the chat on Lokalise platform? Thing is, this repo is for Node SDK only, we don't develop the actual API here. The customer support team can request all the necessary details for this proposal and properly register it within the system. Thank you!
