### ISSUE TITLE
OTA API Support

### ISSUE THREAD

**Issue by DevNico** [lokalise/node-lokalise-api#397]
Would be great if the SDK also supported the OTA API.

**Comment by bodrovis** [comment]
I'm considering it, actually! For now it's possible to request JWT https://lokalise.github.io/node-lokalise-api/api/jwt But hopefully new methods will be added soon

**Comment by bodrovis** [comment]
This feature is now available in v11. Please refer to the following guide to get started https://lokalise.github.io/node-lokalise-api/ota/introduction Specifically, please note that these new endpoints require the usage of a separate client (as it requires JWT, not a Lokalise API token).
