### ISSUE TITLE
 Cannot find module 'got' or its corresponding type declarations.

### ISSUE THREAD

**Issue by unxavi** [lokalise/node-lokalise-api#405]
**Describe the bug**
Updated a project from v8 to v11.0.1. Implementation of the SDK is quite simple. When building the project we get the follwoing:

```
node_modules/@lokalise/node-api/dist/collections/base_collection.d.ts:1:25 - error TS2307: Cannot find module 'got' or its corresponding type declarations.

1 import { Options } from "got";
                          ~~~~~

node_modules/@lokalise/node-api/dist/http_client/base.d.ts:1:25 - error TS2307: Cannot find module 'got' or its corresponding type declarations.

1 import { Options } from "got";

```

**To Reproduce**
Build the project with TS

**Expected behavior**
Build the project

**Your environment:**
 - Node version 16.17.1

**Additional context**

**Comment by bodrovis** [comment]
I can't reproduce this problem, unfortunately. Can you please share a repo where I can observe this issue? Please note that v11 is a ESM module so your project should  be configured accordingly. If that's not possible, usually dynamic imports do the trick

```ts
(async function () {
  const LokaliseApi = await (import('@lokalise/node-api').then(m => m.LokaliseApi));
  const lokaliseApi = new LokaliseApi({ apiKey: LOKALISE_API_TOKEN});

  // use lokaliseApi here as usual...
})();
```

**Comment by bodrovis** [comment]
Actually, it might be related to the following issue: https://github.com/sindresorhus/got/issues/2267 They recommend to add ` "module": "node16", "moduleResolution": "node16"` inside tsconfig.

**Comment by bodrovis** [comment]
Hopefully one of the fixes suggested in that issue should do the trick, please let me know. To be honest, I'm really concerned about all these recurring issues with Got and I'm actually considering getting rid of it

**Comment by bodrovis** [comment]
So, I've looked into it further and for now decided to revert to Got 12. Therefore you can install the latest Lokalise Node SDK v11.1.0 which should hopefully work better. I'm planning to get rid of Got in one of the next major releases and replace it with Fetch API. Unfortunately, it's not a very simple thing to do because tests will also have to be re-written to properly mock the responses.
