### ISSUE TITLE
WebhookProjectTranslationUpdated and WebhookProjectTranslationProofread are missing the "action" field

### ISSUE THREAD

**Issue by stalar** [lokalise/node-lokalise-api#462]
**Describe the bug**
The types WebhookProjectTranslationUpdated and WebhookProjectTranslationProofread are missing the "action" field.

**Comment by bodrovis** [comment]
From what I can see, `project.translation.updated` does not have an `action` field, at least I don't see one when firing this webhook. Do you observe a different result?

**Comment by stalar** [comment]
I think all webhook events should have an `action` field to tell where the event originated from.

**Comment by stalar** [comment]
If action is not available on these events, then this bug report is about that :-)

**Comment by stalar** [comment]
Although not documented, we expect `action === 'api'` whenever the event was sent as a result of us calling the api

**Comment by bodrovis** [comment]
I don't think `action` is present for all events, to be honest. I'll reach out to the team but if that's the case then we'll need to raise this request elsewhere (as it's not related to the sdk itself). Sorry for this confusion, I'll ask the team now

**Comment by bodrovis** [comment]
I've forwarded this request to the corresponding team, and will let you know once this is resolved 👍

**Comment by bodrovis** [comment]
I had a chat with the team who's managing these webhooks and unfortunately it does not seem this will be resolved soon. They've added it to the pipeline but I really can't say for sure what's the ETA. If this feature is important for you, I'd recommend talking to csm or the support team directly to provide more context

**Comment by stalar** [comment]
Thanks for your help!

**Comment by bodrovis** [comment]
I've received a response from the team, they're saying that the `action` is only expected to be present for certain bulk actions. If this feature is required, I'd recommend reaching out directly to the customer support or csm so that they can properly handle feature request. Sorry for this! :(
