### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by loick** [lokalise/node-lokalise-api#491]
Hi 👋

Is it possible to add a changelog along with the new releases? It would be easier to understand the implication(s) of the update. 

A minor version has been released recently but I have no idea the impact it could have on my codebase. 

Thanks! 🙏

**Comment by bodrovis** [comment]
Good day! The changelog can be found here: https://lokalise.github.io/node-lokalise-api/additional_info/changelog But actually I thought to mention key points in the Releases tab as well. Do let me know if you have any questions regarding a specific version, I can explain changes in more detail 👍

**Comment by bodrovis** [comment]
Feel free to reopen this if something seems unclear!
