### ISSUE TITLE
X-Total-Count missing from `new LokaliseApi().keys.list`

### ISSUE THREAD

**Issue by jamesjones93** [lokalise/node-lokalise-api#53]
**Describe the bug**
The total count of keys is missing from the response from `new LokaliseApi().keys.list`

**To Reproduce**
Call `new LokaliseApi().keys.list` 

**Expected behavior**
Expose `X-Total-Count` to a property in the response from `new LokaliseApi().keys.list`

**Your environment:**
 - Node version: v12.13.0
- "@lokalise/node-api": "^5.3.0",

**Additional information:**
From [this issue](https://github.com/lokalise/node-lokalise-api/issues/12) we found some headers had been added, but not including `X-Total-Count`

CC @ycmjason

**Comment by bodrovis** [comment]
Thank you for reporting this, I'll check asap!

**Comment by bodrovis** [comment]
Meanwhile, I would recommend the following approach:

```ts
const keys = await lokaliseApi.keys.list({
        project_id: project_id,
        page: 2,
        limit: 3,
      });

lokaliseApi.keys.totalResults; // => should return total results properly

**Comment by jamesjones93** [comment]
Thank you @bodrovis !

**Comment by bodrovis** [comment]
Okay, so we've discussed this, and for now the above approach is the only available one, but it should work properly for all collections that have pagination data. However, in the near future we'll work on a slightly different approach for obtaining pagination data. This will be a breaking change but nothing too serious. :)

**Comment by bodrovis** [comment]
Please note that this issue is resolved in node SDK v6 which was released a couple of days ago. Now it's possible to fetch `totalResults` and other  data directly from the objects (for example, `projects.totalResults`). However, this version has some breaking changes so please check the changelog https://lokalise.github.io/node-lokalise-api/additional_info/changelog

**Comment by jamesjones93** [comment]
Thank you @bodrovis 🎉 !!
