### ISSUE TITLE
A way to know if a dataset was changed since last request

### ISSUE THREAD

**Issue by basharov** [lokalise/node-lokalise-api#7]
**Request an updated dataset only if it was changed**

**Additional context**
Imagine, I retrieve `translations` for the project.
The dataset is retrieved and I save it locally.
Now, I pass this locally-stored dataset to to my logic.

Next, someone changes some translation via Lokalise interface.
I don't know if translations were changed or not until I retrieve the whole dataset again, so I tend to request it every time to make sure it's up-to-date.

It would be great to have some endpoint like `/projects/<PROJECT_ID>/translations/summary` which would have a timestamp of the last change so next time before deciding if need to fetch the whole dataset or not, I compare its timestamp to the local timestamp.

Any advice if it's possible now?

Thanks!

**Comment by bodrovis** [comment]
Thank you, we will consider this enhancement. Please note by the way that we have a dedicated site https://vote.lokalise.com/ where customers may suggest their ideas. Cheers! :)

**Comment by bodrovis** [comment]
I will go ahead and close this issue. After all, tracker is meant to discuss library-specific questions, not general features like this one. Still, I really think this is a great idea and so please post it at https://vote.lokalise.com/ if you have a couple of minutes! I've also notified other team members.
