### ISSUE TITLE
Feature to allow download files from a specific branch of Branches Beta

### ISSUE THREAD

**Issue by iagorm** [lokalise/node-lokalise-api#9]
The new beta Branches is an amazing way to tidy the translations, it would be fantastic if `lokaliseApi.files.download` accept as second argument on the property of `DownloadFileParams` a branch to download it.

**Comment by bodrovis** [comment]
I'm pretty sure it should work if you just specify branch with the project id, like `3002780358964f9bab5a92.87762498:feature/new-release`. If that does not work, please let me know!

**Comment by iagorm** [comment]
> I'm pretty sure it should work if you just specify branch with the project id, like `3002780358964f9bab5a92.87762498:feature/new-release`. If that does not work, please let me know!

@bodrovis it worked like a charm! Thank you!

**Comment by bodrovis** [comment]
Oh, great. I will update README to include this info. Cheers!
